### ISSUE TITLE
File provider stats continually climb

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#6]
## Describe the bug
Between version 0.5.6-beta2 and 0.5.6-beta4, the size and limit of the file providers now continually grows. It doesn't seem to leak any more memory than before, but we do still leak memory and crash.

## Expected behavior
The file size doesn't change, so I wouldn't expect the provider to just grow and grow

## Config file
[RmsReadOnly.yaml](https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/RMS/RmsReadOnly.yaml)

## Command to run
*Enter below the full command used to execute Pewpew.*

```sh
# pewpew run -f json -w RmsReadOnly.yaml
```

## System info
 - Operating System: Amazon Linux
 - Pewpew version: 0.5.6-beta4

## Additional context
0.5.6-beta2 - [PewPew Agent Dashboard](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.timeSelector.earliest=1588604150&form.timeSelector.latest=1588607760&form.envSelector=rmsreadonlystage&form.agentSelector=pewpewagent-devxl-app-36-238-188)
0.5.6-beta4 - [PewPew Agent Dashboard](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.timeSelector.earliest=1589383010&form.timeSelector.latest=1589387010&form.envSelector=rmsreadonlystage&form.agentSelector=pewpewagent-devxl-app-36-237-160)

I was also able to repro this with my simpler Permissions file which only has about 3 API calls
[PewPew Agent Dashboard](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.envSelector=rmsgetpermissionsstage20200518T180831538&form.timeSelector.earliest=1589825558&form.timeSelector.latest=1589829171&form.agentSelector=pewpewagent-dev-app-36-238-160)
[RmsGetPermissions.yaml](https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/RMS/RmsGetPermissions.yaml)

**Comment by EliSnow** [comment]
Fixed in beta 5
