### ISSUE TITLE
pewpew 5.6 beta 4 hangs consistently on test after about 30 minutes

### ISSUE THREAD

**Issue by tkmcmaster** [FamilySearch/pewpew#7]
## Describe the bug
Our Ingest test (that tests a bunch of POSTs and PUTs ) which uses a lot of providers to pass data worked fine on 0.5.6 beta 2 but has been consistently hanging after 30ish minutes and no longer writes to stdout, stderr, or sends any network traffic.

## Expected behavior
The test should run for the full duration and exit gracefully.

## Config file
[RmsIngest.yaml](https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/RMS/RmsIngest.yaml)
[RmsAll.yaml](https://github.com/fs-eng/SystemTestTools/blob/master/pewpewtests/RMS/RmsAll.yaml)

## Command to run

```sh
# pewpew -f json -w RmsIngest.yaml
```

## System info
 - Operating System: Amazon Linux
 - Pewpew version: 0.5.6-beta4

## Additional context
[Ingest Only Run](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.envSelector=rmsingeststage20200518T150401939&form.timeSelector.earliest=1589814486&form.timeSelector.latest=1589817957&form.agentSelector=pewpewagent-dev-app-36-236-203)
[All Apis Run](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.envSelector=rmsallstage20200518T163251178&form.timeSelector.earliest=1589819577&form.timeSelector.latest=1589821822&form.agentSelector=pewpewagent-devlg-app-36-237-117)
[All Apis Run](https://familysearch.splunkcloud.com/en-US/app/QA/pewpew_agent_dashboard?form.envSelector=rmsallstage20200519T025221049&form.timeSelector.earliest=1589856983&form.timeSelector.latest=1589860313&form.agentSelector=pewpewagent-devlg-app-36-225-210)

Those are the runs that all hung up on beta4. Ron was trying to run the tests yesterday and kept pinging me to see what was going on. I finally suggested he try the 9xl and just run it all on one box rather than try to synchronize two runs (the ingest can't be restarted on crash). Since we've moved back to beta2 we haven't had ingest hang on us.

**Comment by EliSnow** [comment]
Fixed on beta 5
